#!/bin/bash

CONFIG_FOLDER="/etc/kos32-gcc"
INSTALL_PATH_FILE="$CONFIG_FOLDER/install-path"
DEFAULT_TOOLCHAIN_DIR="/home/autobuild/tools"


TOOLCHAIN_DIR=$(head -n 1 $INSTALL_PATH_FILE)

rm -Rf $TOOLCHAIN_DIR

rm -Rf /home/autobuild

FULL_PATH="$TOOLCHAIN_DIR/win32/bin"
CHR="/"
REPLACE_TO="\/"

MESSAGE="${FULL_PATH//$CHR/"$REPLACE_TO"}"

sudo sed -i -e '/'$MESSAGE'/d' /etc/profile
