#!/bin/bash

CONFIG_FOLDER="/etc/kos32-gcc"
INSTALL_PATH_FILE="$CONFIG_FOLDER/install-path"
DEFAULT_TOOLCHAIN_DIR="/home/autobuild/tools"


TOOLCHAIN_DIR=$(head -n 1 $INSTALL_PATH_FILE)

rm -Rf $TOOLCHAIN_DIR

rm -Rf /home/autobuild
